# Generated by Django 2.2 on 2019-07-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
